image: node:14.15.4

pages:
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules/.cache
  only:
    - main
  script:
    - yarn
    - yarn build
    - rm -rf public
    - mv build public
  stage: deploy
