image: node:14.15.4

stages:
  - build_and_deploy

build:
  stage: build_and_deploy
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - rm -rf public
    - mv build public
  only:
    - test

  artifacts:
    paths:
      - public
