stages:
  - build
  - deploy

build:
  image: node:16.13.2
  stage: build
  variables:
    PUBLIC_URL: /ant_community_frontend_dev3
  script:
    - yarn install --frozen-lockfile
    - yarn build
  only:
    - test
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv build public
  artifacts:
    paths:
      - public
