image: node:14.15.4

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
  only:
    - test
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mv build public
  artifacts:
    paths:
      - public
