image: node:14.15.4
stages:
  - build
  - deploy

build test to production:
  stage: build
  only:
    - test
  script:
    - yarn install --frozen-lockfile
    - yarn build

deploy test to production:
  stage: deploy
  only:
    - test
  artifacts:
    paths:
      - build
